apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: main-service
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
