name: ai-trust-game

include:
  - compose.postgres.yml
  - compose.rabbitmq.yml
  - compose.auth-service.yml
  - compose.game-service.yml
  - compose.logging-service.yml
  - compose.audit-service.yml
  - compose.gateway-service.yml
  - compose.frontend-web.yml
