apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.auth.password | quote }}
