apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-entry
  namespace: atg-dev
  labels:
    app.kubernetes.io/name: app-entry
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: ai-trust-game
    app.kubernetes.io/environment: dev
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /analysis
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 8080
          - path: /chat
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 8080
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: main-service
                port:
                  number: 8080
          - path: /interaction
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 8080
          - path: /logs
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 8080
          - path: /session
            pathType: Prefix
            backend:
              service:
                name: main-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-web
                port:
                  number: 80
