apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/component: {{ .Values.component }}
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: http
      nodePort: {{ .Values.nodePort }}
