apiVersion: v1
kind: ConfigMap
metadata:
  name: main-service-config-map
  labels:
    app.kubernetes.io/name: main-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ai-trust-game
data:
  APP_ENV: dev
  PORT: "8080"
  LLM_PROVIDER: static
  GROQ_MODEL: ""
