apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  POSTGRES_DB: {{ .Values.auth.database | quote }}
