name: CI Test PR

on:
  pull_request:
    branches:
      - test

jobs:
  go-checks:
    uses: ./.github/workflows/reusable-go.yml

  flutter-checks:
    uses: ./.github/workflows/reusable-flutter.yml
    with:
      flutter-version: "3.41.2"

  helm-checks:
    uses: ./.github/workflows/reusable-helm.yml
    with:
      chart-path: ./infrastructure/k8s/service-chart
      values-files: |
        ./services/gateway-service/k8s/values-dev.yaml
        ./services/gateway-service/k8s/values-test.yaml
        ./services/gateway-service/k8s/values-prod.yaml
        ./services/game-service/k8s/values-dev.yaml
        ./services/game-service/k8s/values-test.yaml
        ./services/game-service/k8s/values-prod.yaml
        ./services/logging-service/k8s/values-dev.yaml
        ./services/logging-service/k8s/values-test.yaml
        ./services/logging-service/k8s/values-prod.yaml
        ./services/audit-service/k8s/values-dev.yaml
        ./services/audit-service/k8s/values-test.yaml
        ./services/audit-service/k8s/values-prod.yaml
        ./apps/trust-game-app/k8s/values-dev.yaml
        ./apps/trust-game-app/k8s/values-test.yaml
        ./apps/trust-game-app/k8s/values-prod.yaml

  helm-entry-checks:
    uses: ./.github/workflows/reusable-helm.yml
    with:
      chart-path: ./infrastructure/k8s/entry-chart
      values-files: |
        ./apps/trust-game-app/k8s/entry-values-dev.yaml
        ./apps/trust-game-app/k8s/entry-values-test.yaml
        ./apps/trust-game-app/k8s/entry-values-prod.yaml

  docker-build-gateway-service:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      job-name: Docker Build Gateway Service
      dockerfile: ./infrastructure/docker/go-service.Dockerfile
      build-args: |
        SERVICE=gateway-service

  docker-build-game-service:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      job-name: Docker Build Game Service
      dockerfile: ./infrastructure/docker/go-service.Dockerfile
      build-args: |
        SERVICE=game-service

  docker-build-logging-service:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      job-name: Docker Build Logging Service
      dockerfile: ./infrastructure/docker/go-service.Dockerfile
      build-args: |
        SERVICE=logging-service

  docker-build-audit-service:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      job-name: Docker Build Audit Service
      dockerfile: ./infrastructure/docker/go-service.Dockerfile
      build-args: |
        SERVICE=audit-service

  docker-build-frontend-web:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      job-name: Docker Build Frontend Web
      dockerfile: ./infrastructure/docker/flutter-web.Dockerfile
      build-args: |
        APP_ENV=dev
        API_BASE_URL=http://raspberrypi.tail164eef.ts.net:30080
